[package]
name         = "cgp-serde-tests"
version      =  "0.2.0"
edition      = { workspace = true }
license      = { workspace = true }
repository   = { workspace = true }
authors      = { workspace = true }
rust-version = { workspace = true }
keywords     = { workspace = true }
description  = "Tests for the cgp-serde crates"
publish      = false

[dependencies]
cgp                     = { workspace = true }
cgp-serde               = { workspace = true }
cgp-serde-extra         = { workspace = true }

serde           = { workspace = true, features = ["derive"] }
serde_json      = { workspace = true }
ron             = { workspace = true }
postcard        = { workspace = true }

[dev-dependencies]
trybuild        = { workspace = true }
